<a href="https://colab.research.google.com/github/depeshsikarwar/Data-Science/blob/main/Lec08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [13]:
df1=pd.DataFrame({
    'id':[1,2,3,4,5],
    'name':['a','b','c','d','e'],
    'age':[20,21,22,23,24],
    'city':['a1','a2','a3','a4','a5']
})


df2=pd.DataFrame({
    'id':[3,4,5,6,7],
    'name':['f','g','h','i','j'],
    'age':[25,26,27,28,29],
    'city':['f1','f2','f3','f4','f5']
})
# inner join
# df3=pd.merge(df1,df2,on='id',how='inner',suffixes=('_table1','_table2'))
df3=pd.merge(df1,df2,on='id',how='inner')
df3.rename(columns={'name_x':'table1_name','name_y':'table1_name'},inplace=True)
# print(df3)
# left join
df4=pd.merge(df1,df2,on='id',how='left',suffixes=('_table1','_table2'))
# print(df4)
# right join
df5=pd.merge(df1,df2,on='id',how='right')
# print(df5)
# outer join
df6=pd.merge(df1,df2,on='id',how='outer')
display(df6)

# cross join
df7=pd.merge(df1,df2,how='cross')
# display(df7)

# Concat //up and right join or stake join
df8=pd.concat([df1,df2])
# display(df8)

   id name_x  age_x city_x name_y  age_y city_y
0   1      a   20.0     a1    NaN    NaN    NaN
1   2      b   21.0     a2    NaN    NaN    NaN
2   3      c   22.0     a3      f   25.0     f1
3   4      d   23.0     a4      g   26.0     f2
4   5      e   24.0     a5      h   27.0     f3
5   6    NaN    NaN    NaN      i   28.0     f4
6   7    NaN    NaN    NaN      j   29.0     f5

In [14]:
# DROP DUPLICATES.
df1=pd.DataFrame({
    'id':[1,2,3,4,5],
    'name':['a','b','c','d','e'],
    'age':[20,21,22,23,24],
    'city':['a1','a2','a3','a4','a5']
})


df2=pd.DataFrame({
    'id':[3,4,5,6,7],
    'name':['f','g','h','i','j'],
    'age':[25,26,27,28,29],
    'city':['f1','f2','f3','f4','f5']
})

df3=pd.concat([df1,df2])
df3=df3.drop_duplicates(subset=['id'],keep='last',inplace=True)
display(df3)

None

In [18]:
df=pd.read_csv('student_data.csv')
# pivit table that is made from other data
df.pivot_table(columns='placement_status',index ='sleep_hours',values='exam_score',aggfunc='mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [20]:
df=pd.read_csv('student_data.csv')
df.pivot_table(columns='study_hours',index ='sleep_hours',values='assignments_completed',aggfunc='mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844